theme: jekyll-theme-minimal
title: Second Draft
description: It's not the emotion you experience that help form habits, but the competence and clarity you develop in performing the behavior. That sense of capability produces a feeling of success, which reinforces the desire to repeat it.
excerpt_separator: <!--more-->
